"use client";

export const PANEL_SPECS = {
  songSelector: {
    title: "Song selector",
    tone: "violet",
    minWidthClass: "min-w-[24rem]",
    maxWidthClass: "max-w-full",
    minHeightClass: "min-h-[11rem]",
    className: "w-full shrink-0",
  },
  midiImport: {
    title: "Import MIDI",
    tone: "violet",
    minWidthClass: "min-w-[20rem]",
    maxWidthClass: "max-w-full",
    minHeightClass: "min-h-[9rem]",
    className: "w-full shrink-0",
  },
  nowPlaying: {
    title: "Now playing",
    tone: "sky",
    minWidthClass: "min-w-[20rem]",
    maxWidthClass: "max-w-full",
    minHeightClass: "min-h-[11rem]",
    className: "w-full shrink-0",
  },
  activeNotes: {
    title: "Active notes",
    tone: "sky",
    minWidthClass: "min-w-[24rem]",
    maxWidthClass: "max-w-[34rem]",
    minHeightClass: "min-h-[11rem]",
    className: "h-[11rem] w-[26rem] shrink-0",
  },
  transport: {
    title: "Transport",
    tone: "amber",
    minWidthClass: "min-w-[22rem]",
    maxWidthClass: "max-w-full",
    minHeightClass: "min-h-[11rem]",
    className: "w-full shrink-0",
  },
  settings: {
    title: "Settings",
    tone: "zinc",
    minWidthClass: "min-w-[22rem]",
    maxWidthClass: "max-w-full",
    minHeightClass: "min-h-[22rem]",
    className: "w-full shrink-0",
  },
  volume: {
    title: "Volume",
    tone: "zinc",
    minWidthClass: "min-w-[20rem]",
    maxWidthClass: "max-w-full",
    minHeightClass: "min-h-[6rem]",
    className: "w-full shrink-0",
  },
  metronome: {
    title: "Metronome",
    tone: "emerald",
    minWidthClass: "min-w-[20rem]",
    maxWidthClass: "max-w-full",
    minHeightClass: "min-h-[11rem]",
    className: "w-full grow shrink-0",
  },
  songSummary: {
    title: "Song summary",
    tone: "violet",
    minWidthClass: "min-w-[24rem]",
    maxWidthClass: "max-w-[44rem]",
    minHeightClass: "min-h-[16rem]",
    className: "w-full xl:w-[44rem] shrink-0",
  },
  songInfo: {
    title: "Song info",
    tone: "zinc",
    minWidthClass: "min-w-[24rem]",
    maxWidthClass: "max-w-[44rem]",
    minHeightClass: "min-h-[16rem]",
    className: "w-full xl:w-[44rem] shrink-0",
  },
  songEventsPreview: {
    title: "Events preview",
    tone: "cyan",
    minWidthClass: "min-w-[24rem]",
    maxWidthClass: "max-w-[90rem]",
    minHeightClass: "min-h-[18rem]",
    className: "w-full shrink-0",
  },
  keyboardRoll: {
    title: "Keyboard + roll",
    tone: "cyan",
    minWidthClass: "min-w-[24rem]",
    maxWidthClass: "max-w-[1204px]",
    minHeightClass: "min-h-[24rem]",
    className: "w-full shrink-0 self-center",
    bodyClassName: "p-0",
  },
  diagnostics: {
    title: "Diagnostics",
    tone: "rose",
    minWidthClass: "min-w-[24rem]",
    maxWidthClass: "max-w-[72rem]",
    minHeightClass: "min-h-[16rem]",
    className: "w-full shrink-0",
  },
};

export function getPanelFrameProps(name) {
  return PANEL_SPECS[name] ?? {};
}
